### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by sepej** [saadbruno/servatrice-compose#1]
I keep getting an error that the server cannot open the database file

Sat Feb 6 00:06:20 2021 "[main] Error opening database: Access denied for user 'servatrice'@'172.19.0.3' (using password: YES) QMYSQL: Unable to connect"

I've tried changing the hostname in the .ini and it doesn't seem to change anything.

`Sat Feb 6 00:07:33 2021 Authenticating method: none

Sat Feb 6 00:07:33 2021 Store Replays:  true

Sat Feb 6 00:07:33 2021 Client ID Required:  false

Sat Feb 6 00:07:33 2021 Maximum user limit enabled:  false

Sat Feb 6 00:07:33 2021 Accept registered users only:  false

Sat Feb 6 00:07:33 2021 Registration enabled:  false

Sat Feb 6 00:07:33 2021 Forgot password enabled:  false

Sat Feb 6 00:07:33 2021 Auditing enabled:  true

Sat Feb 6 00:07:33 2021 Audit registration attempts enabled:  true

Sat Feb 6 00:07:33 2021 Audit forgot password attepts enabled:  true

Sat Feb 6 00:07:33 2021 "[main] Opening database..."

Sat Feb 6 00:07:33 2021 "[main] Error opening database: Access denied for user 'servatrice'@'172.19.0.3' (using password: YES) 
QMYSQL: Unable to connect"

Sat Feb 6 00:07:33 2021 Failed to open database`

**Comment by saadbruno** [comment]
There's a few things we can do to troubleshoot this.

1 - What do you see when you run `docker ps`? is the `servatrice_mysql` container running?

2 - in your `servatrice.ini` file, **do not** change anything in the `[database]` section. The hostname, prefix, username, etc is already configured to properly communicate to the mysql container.
The `hostname` in that section should just be `mysql`, since that's the service name in docker.
(If you're already using the hostname "mysql" and need to change it, you have to update it in the `docker-compose.yml` file)

3 - what do you see when running `make logs-mysql`? Do you see `ready for connections`?

**Comment by sepej** [comment]
Yeah, my servatrice_mysql container is running. Here are the logs from that:

servatrice_mysql | 2021-02-06T00:30:08.115198Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.16)  MySQL Community Server - GPL.
servatrice_mysql | 2021-02-06T00:30:11.024446Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
servatrice_mysql | 2021-02-06T00:30:11.024721Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.16) starting as process 1
servatrice_mysql | 2021-02-06T00:30:12.103867Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
servatrice_mysql | 2021-02-06T00:30:12.113154Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
servatrice_mysql | 2021-02-06T00:30:12.167047Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.16'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
servatrice_mysql | 2021-02-06T00:30:12.231427Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060

I haven't touched the [database] section. I left it all the same and put the hostname to mysql. I was just trying my server's local ip and that didn't work. This is the only instance of 'mysql' hostname I have running on my docker.

**Comment by sepej** [comment]
I got it working. I had to delete the mysql/mount directory and make restart-all. Thanks for making this so easy to set up :)
